
import LocaleSwitcher from '@/components/LocaleSwitcher';
// import type { Metadata } from 'next';
import './globals.css';
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body>
        <LocaleSwitcher />
        {children}</body>
    </html>
  );
}
